apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: house-rent
  name: house-rent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: house-rent
  template:
    metadata:
      labels:
        app: house-rent
    spec:
      containers:
      - image: vaishsab/house-rent:1.0.0
        name: webapp
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: house-rent
  ports:
    - port: 8080
      nodePort: 30007